In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv(r"C:\Users\namal\Downloads\heart_2020_cleaned.csv")
data.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30.0,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0.0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30.0,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0.0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0.0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

In [3]:
# import LabelEncoder  changing object type to values[0,1,2..]
from sklearn.preprocessing import LabelEncoder
le_sm = LabelEncoder()
le_al = LabelEncoder()
le_st = LabelEncoder()
le_dw = LabelEncoder()
le_sx = LabelEncoder()
le_ac = LabelEncoder()
le_rc = LabelEncoder()
le_db = LabelEncoder()
le_pa = LabelEncoder()
le_gh = LabelEncoder()
le_as = LabelEncoder()
le_kd = LabelEncoder()
le_sc = LabelEncoder()

In [4]:
data['Smoking'] = le_sm.fit_transform(data['Smoking'])
data['AlcoholDrinking'] = le_al.fit_transform(data['AlcoholDrinking'])
data['Stroke'] = le_st.fit_transform(data['Stroke'])
data['DiffWalking'] = le_dw.fit_transform(data['DiffWalking'])
data['Sex'] = le_sx.fit_transform(data['Sex'])
data['AgeCategory'] = le_ac.fit_transform(data['AgeCategory'])
data['Race'] = le_rc.fit_transform(data['Race'])
data['Diabetic'] = le_db.fit_transform(data['Diabetic'])
data['PhysicalActivity'] = le_pa.fit_transform(data['PhysicalActivity'])
data['GenHealth'] = le_gh.fit_transform(data['GenHealth'])
data['Asthma'] = le_as.fit_transform(data['Asthma'])
data['KidneyDisease'] = le_as.fit_transform(data['KidneyDisease'])
data['SkinCancer'] = le_sc.fit_transform(data['SkinCancer'])

In [5]:
data

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,1,0,0,3.0,30.0,0,0,7,5,2,1,4,5.0,1,0,1
1,No,20.34,0,0,1,0.0,0.0,0,0,12,5,0,1,4,7.0,0,0,0
2,No,26.58,1,0,0,20.0,30.0,0,1,9,5,2,1,1,8.0,1,0,0
3,No,24.21,0,0,0,0.0,0.0,0,0,11,5,0,0,2,6.0,0,0,1
4,No,23.71,0,0,0,28.0,0.0,1,0,4,5,0,1,4,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,Yes,27.41,1,0,0,7.0,0.0,1,1,8,3,2,0,1,6.0,1,0,0
319791,No,29.84,1,0,0,0.0,0.0,0,1,3,3,0,1,4,5.0,1,0,0
319792,No,24.24,0,0,0,0.0,0.0,0,0,5,3,0,1,2,6.0,0,0,0
319793,No,32.81,0,0,0,0.0,0.0,0,0,1,3,0,0,2,12.0,0,0,0
319794,No,46.56,0,0,0,0.0,0.0,0,0,12,3,0,1,2,8.0,0,0,0

In [6]:
X = data.iloc[:,1:]
y = data.iloc[:,0]
display(X,y)

,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,16.60,1,0,0,3.0,30.0,0,0,7,5,2,1,4,5.0,1,0,1
1,20.34,0,0,1,0.0,0.0,0,0,12,5,0,1,4,7.0,0,0,0
2,26.58,1,0,0,20.0,30.0,0,1,9,5,2,1,1,8.0,1,0,0
3,24.21,0,0,0,0.0,0.0,0,0,11,5,0,0,2,6.0,0,0,1
4,23.71,0,0,0,28.0,0.0,1,0,4,5,0,1,4,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,27.41,1,0,0,7.0,0.0,1,1,8,3,2,0,1,6.0,1,0,0
319791,29.84,1,0,0,0.0,0.0,0,1,3,3,0,1,4,5.0,1,0,0
319792,24.24,0,0,0,0.0,0.0,0,0,5,3,0,1,2,6.0,0,0,0
319793,32.81,0,0,0,0.0,0.0,0,0,1,3,0,0,2,12.0,0,0,0
319794,46.56,0,0,0,0.0,0.0,0,0,12,3,0,1,2,8.0,0,0,0

0          No
1          No
2          No
3          No
4          No
         ...
319790    Yes
319791     No
319792     No
319793     No
319794     No
Name: HeartDisease, Length: 319795, dtype: object

In [7]:

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(X,y , test_size = 0.2)
display(x_train,y_train)
display(x_test,y_test)

,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
203963,32.28,0,0,0,0.0,0.0,0,0,10,5,0,0,4,7.0,0,0,0
217218,18.88,0,0,0,1.0,0.0,0,0,9,5,0,1,0,9.0,0,0,0
115540,29.86,0,0,0,0.0,0.0,0,0,9,5,0,1,4,8.0,0,0,0
45177,19.79,0,0,0,0.0,0.0,0,0,6,5,0,1,4,8.0,0,0,0
209688,24.41,1,0,0,14.0,20.0,0,1,4,5,0,1,2,7.0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278908,27.69,1,0,0,0.0,0.0,0,1,11,5,0,1,4,8.0,0,0,0
204875,36.59,0,0,0,0.0,0.0,1,1,5,2,0,0,1,8.0,0,0,0
63511,23.01,0,0,0,0.0,0.0,0,1,8,5,0,1,0,7.0,0,0,0
200969,22.96,0,0,0,0.0,0.0,0,1,8,5,0,1,0,5.0,0,0,0
149950,32.04,1,0,1,10.0,0.0,1,1,7,5,1,1,3,9.0,0,0,0

203963     No
217218     No
115540     No
45177      No
209688     No
         ...
278908    Yes
204875     No
63511      No
200969     No
149950    Yes
Name: HeartDisease, Length: 255836, dtype: object

,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
245862,37.59,0,0,0,0.0,0.0,0,0,7,5,0,1,4,6.0,0,0,0
166650,28.48,0,0,0,0.0,0.0,0,1,1,5,0,1,0,6.0,0,0,0
58227,32.77,0,0,0,0.0,0.0,1,0,6,5,0,1,4,7.0,0,0,0
162659,30.34,0,0,0,1.0,0.0,0,0,11,5,0,1,2,8.0,0,0,0
129319,26.61,0,1,0,0.0,0.0,0,1,3,5,0,1,0,7.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143734,21.02,0,0,0,0.0,0.0,0,1,4,5,0,1,0,8.0,0,1,0
9177,25.61,0,0,0,0.0,0.0,0,0,12,5,0,1,4,7.0,0,0,0
258774,20.38,1,1,0,10.0,12.0,0,0,6,5,0,1,4,5.0,0,0,0
139284,31.89,0,0,0,0.0,1.0,0,0,7,5,0,1,0,6.0,0,0,0
273075,27.26,1,0,0,0.0,5.0,0,0,5,5,3,1,4,5.0,0,1,0

245862    No
166650    No
58227     No
162659    No
129319    No
          ..
143734    No
9177      No
258774    No
139284    No
273075    No
Name: HeartDisease, Length: 63959, dtype: object

In [8]:
from sklearn.neighbors import KNeighborsClassifier

neigh_model = KNeighborsClassifier(n_neighbors = 3)

In [9]:
neigh_model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [10]:
# Predictions

y_pred = neigh_model.predict(x_test)
y_pred

array(['No', 'No', 'No', ..., 'No', 'No', 'No'], dtype=object)

In [11]:
# checking training score 

neigh_model.score(x_train,y_train)

0.9326678028111759

In [12]:
# Testing Score

neigh_model.score(x_test,y_test)

0.8990134304789006

In [13]:
# confusion metrics

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('Accurate Values :',confusion_matrix(y_test,y_pred)[0][0],",",confusion_matrix(y_test,y_pred)[1][1])
print('False Values :',confusion_matrix(y_test,y_pred)[0][1],",",confusion_matrix(y_test,y_pred)[1][0])
print('Total Values :',confusion_matrix(y_test,y_pred)[0][0] + confusion_matrix(y_test,y_pred)[0][1] + confusion_matrix(y_test,y_pred)[1][0] + confusion_matrix(y_test,y_pred)[1][1] )

[[56851  1640]
 [ 4819   649]]
Accurate Values : 56851 , 649
False Values : 1640 , 4819
Total Values : 63959